package org.elasticsearch.omg.support;


import java.lang.annotation.*;

/**
 * Defines how the Id for a {@link ElasticSearchDocument} will work.
 */
@Documented
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ElasticSearchDocumentId {

    /**
     * @return true if this id should be autogenerated by elastic search
     */
    boolean autoGenerate() default false;
}
